# Generated by Django 4.1.7 on 2023-08-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_userprofile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_list_item',
        ),
    ]
