# Generated by Django 4.1.7 on 2023-08-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_remove_teacher_subject_list_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='paid_classes',
        ),
    ]
