# Generated by Django 4.1.7 on 2023-08-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0011_subjectclass_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectclass',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')], max_length=1),
        ),
        migrations.CreateModel(
            name='ExtraClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_from_date', models.DateField(blank=True, null=True)),
                ('moved_from_start_time', models.TimeField(blank=True, null=True)),
                ('moved_to_date', models.DateField(blank=True, null=True)),
                ('moved_to_start_time', models.TimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Отменен'), (1, 'Добавлен'), (0, 'Перенесен')], max_length=2)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.subject')),
            ],
        ),
    ]
