# Generated by Django 4.1.7 on 2023-08-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0012_alter_subjectclass_day_extraclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraclass',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Отменен'), (1, 'Добавлен'), (0, 'Перенесен')]),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')]),
        ),
    ]
