# Generated by Django 4.1.7 on 2023-08-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0014_availabletimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Взрослый'),
        ),
        migrations.AddField(
            model_name='student',
            name='rmv',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='moved_from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='moved_from_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='moved_to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='moved_to_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='extraclass',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Отменен'), (1, 'Добавлен'), (0, 'Перенесен')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Контакт студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Контакт родителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия родителя'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.student', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.subjectlist', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.teacher', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='subjectclass',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='subjectlist',
            name='subject_list_item',
            field=models.CharField(max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
