# Generated by Django 4.1.7 on 2023-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_student_is_adult_student_rmv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rmv',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
    ]
